# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 8080
  connection-timeout: 5000ms

redis:
  captcha:
    prefix: 'baseApi:captcha:'
    expire: 1  # 验证码过期时间，单位分钟
  token:
    prefix: 'baseApi:token:'
    expire: 600  # token有效时长，单位分钟
    enable: true # 校验token开关，true开启token
    secret: BaseApi  #密匙

#短信发送配置
phone:
  sid: 9c1234485b5a369d5dca1cd412e65344
  token: 023b737e0a7c120aa2d95a1fa6d0a341
  appid: 90e27d37954d4716aabaf68f091027bf
  templateid: 447566

#swagger配置
swagger:
  title: '基础API'
  description: 'BaseApi'
  version: '1.0'
  basePackage: 'com.base.controller' #指定swagger扫描包

druid:
  manager:
    username: 'admin'
    password: '123456'
#日志配置
log:
  path: logs  #日志存放位置，可以为相对路径也可以为绝对路径（/）
  projectName: BaseApi #日志存放目录名（一般设置为项目名）
  level: DEBUG   #打印日志级别  < DEBUG < INFO < WARN < ERROR

# MyBatis
mybatis:
    # 搜索指定包别名
    typeAliasesPackage: com.base
    # 配置mapper的扫描，找到所有的mapper.xml映射文件
    mapperLocations: classpath:mapper/**/*Mapper.xml
    # 加载全局的配置文件
    configLocation: classpath:mapper/mybatis-config.xml


# 数据源配置
spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.jdbc.Driver
        druid:
            # 主库数据源
            master:
                url: jdbc:mysql://javazhangwei.top:3306/TeachingAssessment?useSSL=false&useUnicode=true&characterEncoding=utf8
                username: root
                password: qq8061605
            # 从库数据源
            slave:
                # 从数据源开关/默认关闭
                enabled: false
                url:
                username:
                password:
            # 初始连接数
            initialSize: 5
            # 最小连接池数量
            minIdle: 10
            # 最大连接池数量
            maxActive: 20
            # 配置获取连接等待超时的时间
            maxWait: 60000
            # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
            timeBetweenEvictionRunsMillis: 60000
            # 配置一个连接在池中最小生存的时间，单位是毫秒
            minEvictableIdleTimeMillis: 300000
            # 配置一个连接在池中最大生存的时间，单位是毫秒
            maxEvictableIdleTimeMillis: 900000
            # 配置检测连接是否有效
            validationQuery: SELECT 1 FROM DUAL
            testWhileIdle: true
            testOnBorrow: false
            testOnReturn: false
            statViewServlet:
                enabled: true
                url-pattern: /druid/*
            filter:
                stat:
                    # 慢SQL记录
                    log-slow-sql: true
                    slow-sql-millis: 1000
                    merge-sql: true
                wall:
                    config:
                        multi-statement-allow: true
#配置邮件发送
    mail:
      host: "smtp.qq.com"
      username: "javaserve@qq.com"
      password: "itkefyhhytaojfba"
      default-encoding: "utf-8"
    redis:
  #    database: 0 #Redis数据库索引（默认为0）
      host: 47.103.20.104 # Redis服务器地址
      port: 6379 # Redis服务器连接端口
      password: qq80616059. # Redis服务器连接密码（默认为空）
      timeout: 15s # 连接超时时间（毫秒）
      jedis:
        pool:
          max-active: 10 # 连接池中的最小空闲连接
          max-wait: 6s # 连接池最大阻塞等待时间（使用负值表示没有限制）
          max-idle: 20 # 连接池中的最大空闲连接
          min-idle: 0 # 最大活跃连接数，负数为不限制
